name: "Lighthouse: Website Performance Check"
on: [pull_request]

jobs:
  get-deployment-url:
    runs-on: ubuntu-latest
    steps:
      - name: Get Deployment URL
        uses: dorshinar/get-deployment-url@v1.0.0
        timeout-minutes: 5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
  run-lighthouse:
    runs-on: ubuntu-latest
    needs: get-deployment-url
    steps:
      - name: Run Lighthouse
        uses: foo-software/lighthouse-check-action@master
        with:
          accessToken: ${{ secrets.GITHUB_TOKEN }}
          author: ${{ github.actor }}
          urls: ${{ steps.get-deployment-url.outputs.deployment }}
          sha: ${{ github.sha }}

