name: "Lighthouse: Website Performance Check"
on: [pull_request]

jobs:
  run-lighthouse:
    runs-on: ubuntu-latest
    steps:
      - run: echo Running Lighthouse check on https://gigabowser-git-${{github.event.pull_request.head.ref}}.tamudatathon.now.sh
      - name: Run Lighthouse
        uses: foo-software/lighthouse-check-action@master
        with:
          accessToken: ${{ secrets.GITHUB_TOKEN }}
          author: ${{ github.actor }}
          urls: https://gigabowser-git-${{github.event.pull_request.head.ref}}.tamudatathon.now.sh
          sha: ${{ github.sha }}

