name: "Lighthouse: Website Performance Check"
on: [pull_request]

jobs:
  wait-for-vercel-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for deployment
        uses: fountainhead/action-wait-for-check@v1.0.0
        id: wait-for-deployment
        timeout-minutes: 5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: Vercel
          ref: github.event.pull_request.head.sha || github.sha
  run-lighthouse:
    runs-on: ubuntu-latest
    needs: wait-for-vercel-deployment
    steps:
      - name: Run Lighthouse
        uses: foo-software/lighthouse-check-action@master
        with:
          accessToken: ${{ secrets.GITHUB_TOKEN }}
          author: ${{ github.actor }}
          urls: "https://gigabowser-git-${GITHUB_REF##*/}.tamudatathon.now.sh"
          sha: ${{ github.sha }}

